### ISSUE TITLE
Can't run showcase.automotive on automotive Q emulator

### ISSUE THREAD

**Issue by mani-w3w** [android/car-samples#16]
when I run the showcase.automotive module on my Android Emulator with Android 10.0 (Automotive with Play Store) all it shows is a screen saying that "System requires update. Please check for updates, or contact the device manufacturer" click update button but all it does is open the play store nothing more.

and I'm getting this stack trace on my logcat:
`2021-06-22 16:58:24.492 7602-7602/androidx.car.app.sample.showcase E/CarApp.Act: Service error: HOST_NOT_FOUND
    java.lang.Exception: No handlers found for intent: Intent { act=android.car.template.host.RendererService }
        at androidx.car.app.activity.ServiceConnectionManager.bind(ServiceConnectionManager.java:195)
        at androidx.car.app.activity.CarAppViewModel.bind(CarAppViewModel.java:103)
        at androidx.car.app.activity.CarAppActivity.onCreate(CarAppActivity.java:235)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`
        
I might have missed something, can someone help me with this?

**Comment by mani-w3w** [comment]
Any help with this?

**Comment by mani-w3w** [comment]
![Screenshot_1624897978](https://user-images.githubusercontent.com/67689862/123672204-f9759b80-d836-11eb-8122-ba764fd8b8a9.png)

This is the message shown on the emulator, clicking update just opens google play store but nothing happens. 

Thanks, 
Emanuel
